language: node_js
node_js:
  - "lts/Carbon"

addons:
  sonarcloud:
    organization: "ferzerkerx-github"
    token:
      secure: "vj/OoZsREfMUSxMvK226GnwIrNE2h89yE1M21zl7EFf/rN7xu6OYSg99frVVcFLEVWzLD14T52cfyWK3xVTXOSEba24C6tdp+2mabid46GNc7Z+TwUfeNz6q+b5aze3l9oP9lcAARbuZUmVKAdCw+7W+KWv+dYK5Xpp0l1QvST9VytYBP06fHksfSH4OrD/yRCasxV9tBtleDISA6daq/NJtlSMXYpNAea1ovEySB9gdgJLzlB3DC9cieVtcmQ2iCj6MoHtwGWQpiplsnL5IsKow0zt00/7QD/swLnehsavWsnY0tcQLyZjfcF2LP6dE2e/0SxrIjekZllAAg1asSkpcD4tEjumKqLwvu257BsdIyh4xnCGaUOETFbE+0T7ngZQmGfOCKMabG24sE1GXAa86TRRVFmlriw9wA/FejGY9nFDzd/T1l0fx94R+owGdetVpNosVwacmA9NV5JvuGQycczQ4L3Xiz+EJIkTrjhLHyy267iXKcphloVsTyuwIDATIbEG3nCxpWZp11mkbbwNiYR+W2MgBehZZ7wLtc0AUbU4WlyIcDY/HgOWt4JP9Mv6hLYs0XsGA2W0Du7mH5XJIat+YwY4CZqav9Hl87xsVRi+rIrlttoqmDYjSrYto1D4pWILab6Uz1fOGV9UbOipNDMTGoewj4ohdIDyr4g4="
env:
  secure: "LrA83XZ4Z4/zHygBF5lVEr6m1K4LSJZy7YNU+Nr31aEelbSgrTpn1xdtoXlBqGRAOOWDXiOXs3jZBLP9zem0DHVITOtQ+DInJ64QAhaZcm9/lqsGPrRbbiChXaLawHg7ok6LkUhNcZl6Cz+ojDpsSUj2SY5yGuGgx7isanEKJ6s+bB6mb5xQykpG5w5hl7o6JPBGUpTFH6Whz+HX7PCokOjpOMVlC3hOl6NfM3odDOa0LpdjDfX0N/KzBlGn32YMeUrsx3oaHObGa9MGbxNeEmhwYtG7tUDA7wqwJbdgAP/RpZKnaQ8UpUj4I2Emq4rP0774imHPCNbaIW2HrI0PJVI+KrvRbFeaCunnLQregsdOMKQnIC90Tmr97ayMWaADt0S+RJ5Lx7SBHRuSWm2gHlvKnxM9mO5duryKQAAv/aWQ6xgtySTz6I6P9JOuS5maeKPyrR4f4lAih5VCA2fIKNfEG3A80ZTcXbItjiU29Oyd0W87cUvQxj0kXOgHsBRISyZL/oKpkhFUlWHZbAdX2GbTGFdxA5e4sQK6Lt0sfQdyWvRRbBafj7+eFOJSIwndvFXZX32Q44VMWWNTHosd6CGmW662z5S4+FgHZ3L2Xc9y9ojLi6gj7u3BiIuNg6ZAWBCf6AqdAExu3g5O4wTFfwzBShIxJt2bFZsWoWVUTvA="

cache:
  directories:
    - "node_modules"

install:
  - "yarn install"
  - "npm install -g snyk"

script:
  - "yarn build"
  - "yarn test"
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then sonar-scanner; fi'

after_success:
  - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then snyk monitor; fi'