version: "3.8"

services:
  agile-metrics-service:
    image: agile-metrics-tools
    security_opt:
      - seccomp:unconfined
    depends_on:
      - elk-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - ES_HOST=http://elk-service:9200

  elk-service:
    image: sebp/elk:740
    security_opt:
      - seccomp:unconfined
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"